version: '3'
services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"